### PR TITLE
[CELEBORN-906][FOLLOWUP] Removal of redundant dependency `log4j-slf4j2-impl` from SBT profile `spark-3.4`

### PR DESCRIPTION
**Pull request by cfmcgrady**
### What changes were proposed in this pull request?

As title

### Why are the changes needed?

To address the CI failure introduced in https://github.com/apache/incubator-celeborn/pull/1831, this pull request resolves the issue by removing the `log4j-slf4j2-impl` dependency from SBT profile `spark-3.4`. This change is prompted by the pinning of `slf4j-api` to version 1.7.36, rendering `log4j-slf4j2-impl` unnecessary.

```
[error] Test org.apache.spark.shuffle.celeborn.SortBasedPusherSuiteJ failed: java.lang.NoSuchMethodError: org.apache.logging.slf4j.Log4jLoggerFactory: method <init>()V not found, took 0.0 sec
[error]     at org.slf4j.impl.StaticLoggerBinder.<init>(StaticLoggerBinder.java:53)
[error]     at org.slf4j.impl.StaticLoggerBinder.<clinit>(StaticLoggerBinder.java:41)
[error]     at org.slf4j.LoggerFactory.bind(LoggerFactory.java:150)
[error]     at org.slf4j.LoggerFactory.performInitialization(LoggerFactory.java:124)
[error]     at org.slf4j.LoggerFactory.getILoggerFactory(LoggerFactory.java:417)
[error]     at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:362)
[error]     at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:3[88](https://github.com/apache/incubator-celeborn/actions/runs/5974971986/job/16210071148#step:4:89))
[error]     at org.apache.spark.shuffle.celeborn.SortBasedPusherSuiteJ.<clinit>(SortBasedPusherSuiteJ.java:51)
[error]     ...
[error] Test org.apache.spark.shuffle.celeborn.SortBasedPusherSuiteJ failed: java.lang.NoClassDefFoundError: Could not initialize class org.apache.spark.shuffle.celeborn.SortBasedPusherSuiteJ, took 0.0 sec
[error]     at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[error]     ...
```

### Does this PR introduce _any_ user-facing change?

No

### How was this patch tested?

Pass GA

### CODE REVIEW

**Comment by cfmcgrady** [comment]
cc @pan3793 @waitinfuture

**Comment by pan3793** [comment]
Also cc @zhouyifan279, as he is working for Spark 3.5 adaption

File: project/CelebornBuild.scala [hunk 1]
```diff
@@ -492,30 +492,6 @@ object Spark34 extends SparkClientProjects {
...
   val sparkVersion = "3.4.1"
   val zstdJniVersion = "1.5.2-5"
-
-  lazy val deps = Seq(
-    // Spark Use `log4j-slf4j2-impl` instead of `log4j-slf4j-impl` in SPARK-40511
-    // to fix the error:
-    // ```
-    //   java.lang.NoSuchMethodError: org.apache.logging.slf4j.Log4jLoggerFactory.<init>(Lorg/apache/logging/slf4j/Log4jMarkerFactory;)V
-    // ```
-    "org.apache.logging.log4j" % "log4j-slf4j2-impl" % "2.19.0" % "test"
```
Comment (pan3793) [inline project/CelebornBuild.scala:502]: it's a transitive dep of spark-core, have you explicitly excluded it?

Comment (cfmcgrady) [reply project/CelebornBuild.scala:502]: it is not found in the current dependency tree.

```
$ ./build/sbt -Pspark-3.4 celeborn-client-spark-3/Test/dependencyTree | grep log4j-slf4j
[info]   | | +-org.apache.logging.log4j:log4j-slf4j-impl:2.17.2
[info]   | +-org.apache.logging.log4j:log4j-slf4j-impl:2.17.2
[info]   | +-org.apache.logging.log4j:log4j-slf4j-impl:2.17.2
[info]   | | | +-org.apache.logging.log4j:log4j-slf4j-impl:2.17.2
[info]   | | +-org.apache.logging.log4j:log4j-slf4j-impl:2.17.2
[info]   |   +-org.apache.logging.log4j:log4j-slf4j-impl:2.17.2
```

**Review by pan3793 — APPROVED** [review]
I'm going to merge it to recover the CI of main branch
