### PR TITLE
[CELEBORN-912] Support build with Spark 3.5

### PR DESCRIPTION
**Pull request by zhouyifan279**
### What changes were proposed in this pull request?

Support build with Spark 3.5

### Why are the changes needed?

Keep up with upstream.

### Does this PR introduce _any_ user-facing change?

No

### How was this patch tested?

Build with `mvn` and `sbt` locally.

### CODE REVIEW

File: pom.xml [hunk 1]
```diff
@@ -991,6 +996,27 @@
...
+        <module>client-spark/common</module>
+        <module>client-spark/spark-3</module>
+        <!-- TODO solve compilation error when build spark-3-columnar-shuffle with Spark 3.5 -->
+        <!-- <module>client-spark/spark-3-columnar-shuffle</module> -->
+        <module>client-spark/spark-3-shaded</module>
+        <module>tests/spark-it</module>
+      </modules>
+      <properties>
+        <jackson.version>2.15.2</jackson.version>
+        <jackson.databind.version>2.15.2</jackson.databind.version>
```
Comment (cfmcgrady) [inline pom.xml:1011]:
```suggestion
```

Comment (zhouyifan279) [reply pom.xml]: done

**Review by pan3793 — APPROVED** [review]

**Comment by pan3793** [comment]
Thanks, merging to main
